spring:
  data:
    mongodb:
      database: graphgl
  main:
    lazy-initialization: true

graphql:
  spqr:
    http:
      enabled: true
      endpoint: 'graphql'
    gui:
      enabled: true
      endpoint: gui
    ws:
      enabled: false

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#    org.springframework.data.mongodb.repository.Query=DEBUG
logging:
  level:
    org:
      springframework:
        security: DEBUG
